AppColetor/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('add/coletor/', addcoletor, name='addcoletor'),
    path('add/user/', adduser, name='adduser'),
    path('controle/', controle, name='controle'),
    path('search/user/<str:cracha>', search_user, name='search'),
    path('update/<int:id>', coletor_retirada, name='coletor_retirada'),
    path('search/coletor/<int:codigo>', search_coletor, name='search_coletor'),
    path('listar_controles/', listar_controles, name='listar_controles'),
    # path('busca_coletor/', busca_coletor, name='busca_coletor'),
    path('entrega/<int:id>/', entrega_coletor, name="entrega_coletor"),
    path('update/<int:id>/', coletor_update, name="coletor_update"),
    path('voltar/<int:id>/', voltar_coletor, name="voltar_coletor"),
    path('history/', history, name="history"),
    path('coletores_list/', listar_coletores, name="coletores_list"),
    path('listar_users/', listar_users, name="listar_users"),
    path('status_coletor_update/<int:id>/', status_coletor_update, name="status_coletor_update"),
    path('status_users_update/<int:id>/', status_users_update, name="status_users_update"),
    path('observacao/<int:id>/', observacao, name="observacao"),
    #primeira opeção trago a url + um ID / na segunda o nome da minha view com as regras. e terceiro um alias.
]

Coletor/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView


urlpatterns = [
    path('', include('login.urls')),
    path(r'', include('AppColetor.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', login, name='login'),
    path('logout/', my_logout, name='logout'),
]

AppColetor/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class CadastroPessoa(models.Model):
    nome = models.CharField(max_length=100)
    cracha = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.nome}"


class Coletores(models.Model):
    NORMAL = 'no'

    STATUS = (
        ('fo', 'Fornecedor'),
        ('co', 'Condenado'),
        ('de', 'Defeito'),
        ('ma', 'Manutenção'),
        (NORMAL, 'Normal')
    )
    MARCA = (
        ('mo', 'Motorola'),
        ('in', 'Intermec'),
        ('ro', 'Honeywell')
    )

    codigo = models.CharField(max_length=50)
    model = models.CharField(max_length=15)
    marca = models.CharField(max_length=30, choices=MARCA)
    serial_number = models.CharField(max_length=20)
    status = models.CharField(max_length=30, choices=STATUS)

    def __str__(self):
        return f"{self.codigo}"

    @property
    def display_marca(self):
        return self.get_marca_display()


class Controle(models.Model):
    operador = models.ForeignKey(CadastroPessoa, on_delete=models.PROTECT)
    coletor = models.ForeignKey(Coletores, on_delete=models.PROTECT)
    userretirada = models.ForeignKey(User, related_name='usercadastro', on_delete=models.PROTECT)
    dtretirada = models.DateTimeField(auto_now_add=True)
    dtentrega = models.DateTimeField(null=True, blank=True)
    userentrega = models.ForeignKey(User, related_name='userentrega', null=True, blank=True, on_delete=models.PROTECT)
    observacao = models.TextField(null=True, blank=True)

    # def __str__(self):
    #     return f"{self.operador} - {self.coletor}"

AppColetor/views.py
from .forms import *
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from datetime import datetime, timedelta
from django.utils import timezone
from datetime import datetime
from django.db.models import Q

@login_required
def listar_controles(request, template_name="home.html"):
    busca = request.GET.get("busca")  #Pego o conteudo do campo busca do html

    if busca:
        coletores = Controle.objects.filter(Q(coletor__codigo=busca) | Q(operador__cracha=busca)).all()
        return render(request, 'home.html', {'lista': coletores}) # Realiza a pesquisa no banco e traz o valor em home.html

    coletores = Controle.objects.filter(dtentrega__isnull=True).all() #caso branco traz todos disponiveis

    return render(request, template_name, {'lista': coletores})


@login_required
def adduser(request):
    form_user = PessoasForm(request.POST, None)
    if form_user.is_valid():
        form_user.save()
        return redirect('listar_controles')
    return render(request, 'user_new.html', {'form': form_user})


@login_required
def addcoletor(request):
    form_coletor = ColetoresForm(request.POST, None)
    if form_coletor.is_valid():
        form_coletor.save()
        return redirect('listar_controles')
    return render(request, 'coletor_new.html', {'form': form_coletor})

@login_required
def controle(request):
    form_controle = ControleForm(request.POST, None)

    if form_controle.is_valid():
        data = form_controle.cleaned_data
        operador = CadastroPessoa.objects.get(cracha=data.get("cracha"))
        coletor = Coletores.objects.get(codigo=data.get("codigo"))
        doc = form_controle.save(commit=False)
        doc.operador = operador
        doc.coletor = coletor
        doc.userretirada = request.user
        doc.save()
        # form_controle.save()
        return redirect('listar_controles')
    return render(request, 'controle.html', {'form': form_controle})


def search_user(request, cracha):
    pessoa = get_object_or_404(CadastroPessoa, cracha=cracha)
    return JsonResponse(model_to_dict(pessoa))


def search_coletor(request, codigo):
    coletor = get_object_or_404(Coletores, codigo=codigo)
    data = {'marca': coletor.get_marca_display(), 'serial_number': coletor.serial_number}
    return JsonResponse(data)


@login_required
def coletor_retirada(request, id):
    coletor = get_object_or_404(Controle, pk=id)
    coletor.dtretirada = None
    coletor.userretirada = None
    coletor.save()
    return redirect('listar_controles')


@login_required
def coletor_update(request, id):
    coletor = get_object_or_404(Controle, pk=id)
    coletor.dtentrega = None
    coletor.userentrega = None
    coletor.save()
    return redirect('listar_controles')

@login_required
def status_coletor_update(request, id): # Recebe a reposta da pesquisa + o ID.
    coletor = get_object_or_404(Coletores, pk=id) # Tenta recuperar o objeto que o usuario esta tentando, se não ele retorna o erro de 404 de dado que não exsite)
    # Pego o ID no banco pelo "pk é o ID de cada código do coletor no banco"
    form = ColetoresForm(request.POST or None, instance=coletor) # instanciando o form se Or None(se tiver alguma coisa no banco
    # ele já instancia se não cria um novo, No instance é o valor recuperado da consulta, ou seja o form já inicia com uma instancia do ID.)

    if form.is_valid():
        form.save()
        return redirect('coletores_list')
    return render(request, 'coletor_new.html', {"form": form})

@login_required
def observacao(request, id):
    controle = get_object_or_404(Controle, pk=id)
    form_controle = ControleForm(request.POST or None, instance=controle)
    if form_controle.is_valid():
        data = form_controle.cleaned_data
        operador = CadastroPessoa.objects.get(cracha=data.get("cracha"))
        coletor = Coletores.objects.get(codigo=data.get("codigo"))
        doc = form_controle.save(commit=False)
        doc.operador = operador
        doc.coletor = coletor
        doc.dtentrega = timezone.now()
        doc.userentrega = request.user
        doc.userretirada = request.user
        doc.save()
        return redirect('listar_controles')
    return render(request, 'controle.html',  {"form": form_controle, "entrega": True})

@login_required
def voltar_coletor(request, id):
    coletor = get_object_or_404(Controle, pk=id)
    coletor.dtentrega = None
    coletor.save()
    return redirect('listar_controles')


@login_required
def entrega_coletor(request, id):
    coletor = get_object_or_404(Controle, pk=id)
    coletor.dtentrega = timezone.now()
    coletor.userentrega = request.user
    coletor.save()
    return redirect('listar_controles')

@login_required
def history(request, template_name='list_control.html'):
    dtinicial = request.GET.get("dtinicial")
    dtfinal = request.GET.get("dtfinal")
    if dtinicial and dtfinal:
        dtinicial = f"{dtinicial} 00:00:00"
        dtfinal = f"{dtfinal} 23:59:59"
        dt = Controle.objects.filter(dtretirada__gte=dtinicial, dtretirada__lte=dtfinal)

        return render(request, template_name, {'dados': dt})

    dados = Controle.objects.all().order_by("dtretirada")
    return render(request, 'list_control.html', {'dados': dados})

@login_required
def listar_coletores(request):
    busca = request.GET.get("busca")
    if busca:
        coletor = Coletores.objects.filter(codigo=busca)
        return render(request, 'coletores_list.html', {'dados': coletor})

    coletor = Coletores.objects.all()
    return render(request, 'coletores_list.html', {'dados': coletor})

@login_required
def status_users_update(request, id):
    user = get_object_or_404(CadastroPessoa, pk=id)
    form = PessoasForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('listar_users')
    return render(request, 'user_new.html', {"form": form})

@login_required
def listar_users(request):
    busca = request.GET.get("busca")
    if busca:
        user = CadastroPessoa.objects.filter(Q(nome__icontains=busca) | Q(cracha__icontains=busca)).all()
        return render(request, 'user_list.html', {'dados': user})
    user = CadastroPessoa.objects.all()
    return render(request, 'user_list.html', {'dados': user})

AppColetor/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>

    <style>
        input[type=text] {
            text-transform: uppercase;
        }
    </style>


</head>
<body>

<div class="container">
    {% block main %}{% endblock %}
</div>
{% block script %}
<script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

{% endblock %}
</body>
</html>

AppColetor/templates/coletores_list.html
{% extends 'base.html' %}
{% block title %}Listagem de Coletores{% endblock %}
{% block main %}
    <br>
    <br>

    <nav class="navbar " style="background-color: #2F4F2F;">
        <span class="navbar-brand h1 text-white">KEEPERS LOGÍSTICA - CONTROLE DE COLETORES</span>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="btn btn-outline-success my-2 my-sm-0" href={% url 'controle' %}>Registrar Equipamentos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Informações
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href={% url 'adduser' %}>Cadastro Usuário</a>
                        <a class="dropdown-item" href={% url 'addcoletor' %}>Cadastro Coletor</a>
                        <a class="dropdown-item" href={% url 'coletores_list' %}>Lista de Coletores</a>
                        <a class="dropdown-item" href={% url 'listar_users' %}>Lista de Usuários</a>
                        <a class="dropdown-item" href={% url 'history' %}>Histórico</a>
                        {#                        <div class="dropdown-divider"></div>#}
                        {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                    </div>
                </li>
            </ul>
            <form method="get" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" name="busca" placeholder="Pesquisar"
                       aria-label="Coletor">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>

    <br>
    <br>

    <div class="panel-heading">
        <h3 class="navbar navbar-light mb-0 text-white" style="background-color: #2F4F2F;">Lista de Coletores</h3>

    </div>

    <table class="table table-hover">
        <caption>Lista de Coletores</caption>
        <thead>
        <tr>
            {#                <th scope="row">#</th>#}
            <th scope="col">Código</th>
            <th scope="col">Modelo</th>
            <th scope="col">Marca</th>
            <th scope="col">Número de Série</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        {% for coletor in dados %}
            <tr>

            <td><a href="{% url 'status_coletor_update' coletor.id %}">{{ coletor.codigo }}</a></td>
            <td>{{ coletor.model }}</td>
            <td>{{ coletor.get_marca_display }}</td>
            <td>{{ coletor.serial_number }}</td>
            <td>{{ coletor.get_status_display }}</td>

        {% endfor %}
        </tr>
        </tbody>
    </table>
    <br>
    <a href="{% url 'coletores_list' %}" class="btn btn-primary">Voltar</a>
{% endblock %}

AppColetor/templates/controle.html
{% extends 'base.html' %}
{#{% load bootstrap %}#}
{% load widget_tweaks %}
{% block title %} Controle de Equipamentos {% endblock %}
{% block main %}
    <br>
    <br>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <nav class="navbar " style="background-color: #2F4F2F;">
        <span class="navbar-brand h1 text-white">Retirada de Equipamentos</span>
    </nav>
{#    <form action="{% url 'controle' %}" method="post">#}
    <form method="post">

        {% csrf_token %}
        <div class="card-body">
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="row">
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Matricula</label>
                            {% render_field form.cracha class="form-control" placeholder=form.cracha.label %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Nome Completo</label>
                            {% render_field form.nome class="form-control" placeholder=form.nome.label %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Coletor</label>
                            {% render_field form.codigo class="form-control" placeholder=form.codigo.label %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">S/n</label>
                            {% render_field form.serial class="form-control" placeholder=form.serial.label %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Marca</label>
                            {% render_field form.marca class="form-control" placeholder=form.marca.label %}
                        </div>
                    </div>
                </div>
                {% if entrega and entrega %}
                    <div class="col-md-8">
                        <div class="form-row">
                            <div class="col-md-8">
                                <label for="{{ field.id_for_label }}">Observacao</label>
                                {% render_field form.observacao class="form-control" placeholder=form.observacao.label %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="card-footer bg-transparent">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Salvar
            </button>
            <a href="{% url 'listar_controles' %}" class="btn btn-default">Cancelar</a>
        </div>
    </form>


{% endblock %}

{% block script %}
    {{ block.super }}

    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        });

        $(document).ready(function () {
            $("#id_cracha").blur(function () {
                var matricula = $("#id_cracha").val()
                $.ajax({
                    url: "/search/user/" + matricula,
                    type: "GET",
                    success: function (data) {
                        $("#id_nome").val(data.nome)
                    },
                    error: function () {
                        $("#id_nome").val("")
                    }

                })
            })
            $("#id_codigo").blur(function () {
                var coletor = $("#id_codigo").val()
                $.ajax({
                    url: "/search/coletor/" + coletor,
                    type: "GET",
                    success: function (data) {
                        $("#id_serial").val(data.serial_number)
                        $("#id_marca").val(data.marca)
                    },
                    error: function () {
                        $("#id_serial").val("")
                    }

                })
            })
        })

    </script>


{% endblock %}

AppColetor/templates/home.html
{% extends 'base.html' %}
{% block title %}home{% endblock %}
{% block main %}
    <br>
    <br>

    <nav class="navbar " style="background-color: #2F4F2F;">
        <span class="navbar-brand h1 text-white">KEEPERS LOGÍSTICA - CONTROLE DE COLETORES</span>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="btn btn-outline-success my-2 my-sm-0" href={% url 'controle' %}>Registrar Equipamentos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Informações
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href={% url 'adduser' %}>Cadastro Usuário</a>
                        <a class="dropdown-item" href={% url 'addcoletor' %}>Cadastro Coletor</a>
                        <a class="dropdown-item" href={% url 'coletores_list' %}>Lista de Coletores</a>
                        <a class="dropdown-item" href={% url 'listar_users' %}>Lista de Usuários</a>
                        <a class="dropdown-item" href={% url 'history' %}>Histórico</a>
                        {#                        <div class="dropdown-divider"></div>#}
                        {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                    </div>
                </li>
            </ul>
            <form method="get" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" name="busca" placeholder="Pesquisar"
                       aria-label="Coletor">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>

    <br>
    <br>

    <div class="panel-body">
        <div class="panel-heading">
            <h3 class="navbar navbar-light mb-0 text-white" style="background-color: #2F4F2F;">Controle</h3>
        </div>

        <table class="table table-hover">
            <caption>Lista de Colaboradores/ Equipamentos</caption>
            <thead>
            <tr>
                {#                <th scope="row">#</th>#}
                <th scope="col">Nome</th>
                <th scope="col">Matricula</th>
                <th scope="col">Coletor</th>
                <th scope="col">Status</th>
                <th scope="col">Pendente</th>
            </tr>
            </thead>
            <tbody>
            {% for controle in lista %}
                <tr>

                    <td><a href="{% url 'coletor_update' controle.id %}">{{ controle.operador }}</a></td>
                    <td>{{ controle.operador.cracha }}</td>
                    <td>{{ controle.coletor }}</td>
                    <td>{{ controle.coletor.get_status_display }}</td>

                    {% if controle.dtentrega %}
                        <td><a class="btn btn-small btn-info" href="{% url 'voltar_coletor' controle.id %}"

                        >{{ controle.dtentrega|date:"d/m/Y H:i" }}</a></td>

                    {% else %}
                        <td><a class="btn btn-small btn-danger" href="{% url 'observacao' controle.id %}">
                            Realizar Entrega</a></td>
{#                        <td><a class="btn btn-small btn-danger" href="{% url 'controle' controle.observacao %}">Realizar Entrega</a></td>#}

{#                        <td><a class="btn btn-small btn-danger" href="{% url 'entrega_coletor' controle.id %}">#}
{#                            Realizar Entrega</a></td>#}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <br>
        <br>
        <br>
        <a href="{% url 'logout' %}" class="btn btn-danger">Sair</a>
{% endblock %}

AppColetor/templates/list_control.html
{% extends 'base.html' %}
{% block title %}Listagem de Dados{% endblock %}
{% block main %}
    <br>
    <br>

       <nav class="navbar " style="background-color: #2F4F2F;">
        <span class="navbar-brand h1 text-white">KEEPERS LOGÍSTICA - CONTROLE DE COLETORES</span>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="btn btn-outline-success my-2 my-sm-0" href={% url 'controle' %}>Registrar Equipamentos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Informações
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href={% url 'adduser' %}>Cadastro Usuário</a>
                        <a class="dropdown-item" href={% url 'addcoletor' %}>Cadastro Coletor</a>
                        <a class="dropdown-item" href={% url 'coletores_list' %}>Lista de Coletores</a>
                        <a class="dropdown-item" href={% url 'history' %}>Histórico</a>
                        {#                        <div class="dropdown-divider"></div>#}
                        {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                    </div>
                </li>
            </ul>
            <form method="get" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" name="busca" placeholder="Pesquisar"
                       aria-label="Coletor">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>
    <br>
    <br>

    <div class="panel-body">
<div class="panel-heading">
        <h3 class="navbar navbar-light mb-0 text-white" style="background-color: #2F4F2F;">Histórico</h3>
    </div>

        <div class="shadow p-3 mb-5 bg-white rounded">
    <form method="get" class="form-inline my-2 my-lg-0"  style="text-align: center; margin-top: 100px">
        <h1 class="navbar-brand h1 " >De:</h1>
        <input type="date" name="dtinicial">

        <h1 class="navbar-brand h1 " >  Até:</h1>
        <input type="date" name="dtfinal">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
    </form>
    </div>
    </div>
    <br>
    <div class="row">
        <table class="table table-hover">
        <caption>Histórico de Registros</caption>
            <thead>
            <tr>
                {#                <th scope="row">#</th>#}
                <th scope="col">Nome</th>
                <th scope="col">Matricula</th>
                <th scope="col">Entregou</th>
                <th scope="col">Data Retirada</th>
                <th scope="col">Data Entrega</th>
                <th scope="col">Recebeu</th>
                <th scope="col">Status Equip.</th>
                <th scope="col">Observação</th>
            </tr>
            </thead>
            <tbody>
            {% for controle in dados %}
                <tr>

                <td>{{ controle.operador }}</td>
                <td>{{ controle.operador.cracha }}</td>
                <td>{{ controle.userretirada }}</td>
                <td>{{ controle.dtretirada }}</td>
                <td>{{ controle.dtentrega }}</td>
                <td>{{ controle.userentrega }}</td>
                <td>{{ controle.coletor.get_status_display }}</td>
                <td>{{ controle.observacao }}</td>


            {% endfor %}
            </tr>
            </tbody>
        </table>
    </div>

 <a href="{% url 'listar_controles' %}" class="btn btn-primary">Voltar</a>
    {% endblock %}

AppColetor/templates/user_new.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Cadastro {% endblock %}
{% block main %}
    <br>
    <br>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <h5 class="card-header text-white" style="background-color: #2F4F2F;">Cadastro de Colaboradores</h5>
{#    <form action="{% url 'adduser' %}" method="post">#}
    <form method="post">
        {% csrf_token %}
        <div class="card-body">
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="row">
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Matricula</label>
                            {% render_field form.cracha class="form-control" placeholder=form.cracha.label %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="col-md-8">
                            <label for="{{ field.id_for_label }}">Nome Completo</label>
                            {% render_field form.nome class="form-control" placeholder=form.nome.label %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer bg-transparent">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Salvar
            </button>
            <a href="{% url 'listar_users' %}" class="btn btn-default">Cancelar</a>
        </div>
    </form>

{% endblock %}